### ISSUE TITLE
Suggestion: Lockdown profile

### ISSUE THREAD

**Issue by skeith** [palmtree5/palmtree5-cogs#10]
Currently lockdown cog allow only one global profile, what I am suggesting is, allow to create lockdown profiles which contains different sets of channel to be locked down. Invoking the lockdown would need the profile ID such as `lockdown profile 1`

**Comment by palmtree5** [comment]
I'll add this in the V3 rewrite of the lockdown cog

**Comment by palmtree5** [comment]
Profile system is per-server and done via roles, with `[p]lockdown` taking a profile id and applying the configured role for that profile id to all users with a top role below that role in the hierarchy (as well as applying the role to new joins while the server is locked down, though if something else is desired for handling new joins (kicking them, for example), that could be discussed)

See also https://github.com/palmtree5/palmtree5-cogs/commit/ee4bbcb1d67bade8c3baafd019466a7f5c38c78e
