### ISSUE TITLE
An Idea: mcsvr colors

### ISSUE THREAD

**Issue by mining-d** [palmtree5/palmtree5-cogs#11]
Cog: mcsvr

Description of the Idea: 
colors: red for offline and green for online

**Comment by mining-d** [comment]
`

> 

> 

> `[](`![screenshot_20170919-154825](https://user-images.githubusercontent.com/26934301/30595702-37427862-9d52-11e7-8f10-b0af4911ce12.png)`)`

`

**Comment by mining-d** [comment]
[edited code.zip](https://github.com/palmtree5/palmtree5-cogs/files/1314472/edited.code.zip)

**Comment by atiwiex** [comment]
I suggest forking the repo and add the changes there.

**Comment by mining-d** [comment]
I have only add the color, so palm must only copy and paste.

**Comment by mining-d** [comment]
And sorry, my English is not so good

**Comment by palmtree5** [comment]
This should really be a PR, not an issue
