### ISSUE TITLE
lockdown and unlockdown require different permissions.

### ISSUE THREAD

**Issue by QuickNET-Tech** [palmtree5/palmtree5-cogs#12]
Cog: lockdown

Description of the problem: The initial lockdown has no issues, but when attempting to unlockdown, to bots log says `discord.errors.Forbidden: FORBIDDEN (status code: 403): Missing Permissions`. I'm not sure if this is a mistake or if something is a bit messed up on my side. Giving the bot administrator permissions solves the issue, however I do not wish for the bot to keep those perms. So in order to unlockdown I have to grant the bot admin, unlockdown and then shortly after, revoke admin perms. All the bot is doing (afaik) is modifying roles permissions to speak in text chats so I'm not sure why it can do so in one direction just fine but not the other.

**Comment by palmtree5** [comment]
It shouldn't need administrator permissions. It should just need `Manage channel`

**Comment by QuickNET-Tech** [comment]
Yeah, that was what I had thought, but with that perm, it won't do it without the administrator permissions. The roles as shown in the console posted below are all below the bots role in the hierarchy, though that should not matter afaik. Screenshot of the console output and the discord server settings page showing that the bot has the relevant permission. Will attempt to uninstall and reinstall the cog, but I'm not sure what else I can do. Thanks for the reply.
![desktop screenshot 2017 11 08 - 22 06 46 07](https://user-images.githubusercontent.com/23668071/32587972-4964a5a0-c4d1-11e7-8334-26de533e489d.png)
