### ISSUE TITLE
coventry retrieve: deleting the channel will give an error

### ISSUE THREAD

**Issue by ClaireCruz** [palmtree5/palmtree5-cogs#13]
hello palmtree5, When i used coventry retrieve i got an error while it was deleting the channel the bot made. this below here was the error message.
dont know if its my internet but still wanted to check

Can you please help me out?

![afbeelding](https://user-images.githubusercontent.com/30986819/33189883-7d0b8d7e-d0a7-11e7-9c26-614f2563654f.png)

**Comment by palmtree5** [comment]
That error message leads me to believe that the channel it's trying to delete didn't exist at the time it was trying to delete it.
