### ISSUE TITLE
MCSVR: Add option to update channel description as status

### ISSUE THREAD

**Issue by ElderCub** [palmtree5/palmtree5-cogs#14]
Would it be possible the make the mcsvr cog update a channel's description rather than as a message? I'd like to have it easily visible at all times rather than pinning a message for people to check. Something like  

```#minecraft-server | IP:0.0.0.0:0000, 2/20, Online, Spigot 1.12.2```  

Thanks for checking this out.

**Comment by palmtree5** [comment]
Done in https://github.com/palmtree5/palmtree5-cogs/commit/d532f6f647dbfaae8559adaa8760fcc0ff396d08

That is for [Red V3](https://github.com/Cog-Creators/Red-DiscordBot/tree/V3/develop)

Example: https://i.imgur.com/voAlKrg.png

The options for the server tracker are either text (which uses the channel topic to display the server info, as depicted in the image above) or embeds (which allows for multiple servers to be tracked in one channel). Text is the default mode.
