### ISSUE TITLE
[V3 slowmode] Not working

### ISSUE THREAD

**Issue by retke** [palmtree5/palmtree5-cogs#17]
### Cog 

SlowMode

### Description of the problem

When I use the toggleslow command, it's just... not deleting any message.

**Comment by palmtree5** [comment]
FYI that cog isn't exactly fully tested properly, but the general idea is that:
- If the minimum role isn't set
  - If the user is mod, admin, or guild owner, don't delete
- If the minimum role is set
  - If the user has that role or higher in the hierarchy or is the guild owner, don't delete

But also, I point at the big ol warning at the top of the readme indicating that these are a work in progress and may be incomplete/broken. If you have any further info though (error messages, for example), post them here
