### ISSUE TITLE
Issue with coventry.py

### ISSUE THREAD

**Issue by NoNotNick** [palmtree5/palmtree5-cogs#27]
Thank you for taking the time to come report an issue. To help with this, please fill out the following info. Feel free to include screenshots of error messages as needed.

Cog: coventry.py

Description of the problem:  i am getting this weird error in my console when i retrieve someone ` File "C:\Users\rexal\Desktop\stuff\scripts\gits\trash\cogs\coventry.py", line 107, in _retrieve
    await self.bot.delete_channel(chn)
  File "lib\discord\client.py", line 2189, in delete_channel
    yield from self.http.delete_channel(channel.id)
AttributeError: 'NoneType' object has no attribute 'id'`

https://i.imgur.com/eMo3z9L.png

**Comment by palmtree5** [comment]
Won't fix, not supporting V2 anymore
