### ISSUE TITLE
Hypixel Cog issue

### ISSUE THREAD

**Issue by marioandluigi878** [palmtree5/palmtree5-cogs#6]
Thank you for taking the time to come report an issue. To help with this, please fill out the following info. Feel free to include screenshots of error messages as needed.

Cog: 
HPAPI
Description of the problem: 
When attempting to use the command `hpplayer (ign)` it comes up with this error https://i.imgur.com/6qfzOVC.png

**Comment by palmtree5** [comment]
Try getting an API key by doing /api on the server, then set it using `hpset apikey` followed by the key you got from the server. Then try again, it should work after that

**Comment by marioandluigi878** [comment]
I had already inputted the api key though yet it still gives me the same error when I try to look up the player https://i.imgur.com/7lM7vrI.png

**Comment by palmtree5** [comment]
Try reloading?

**Comment by marioandluigi878** [comment]
....Yep I think i turned into a user (tfts ref) WHY!?! ugh thanks for the help *grumble grumble*
